x-pawpal-common: &pawpal-common
  build: .
  restart: always
  depends_on:
    pawpal_mongodb_dev:
      condition: service_healthy
  environment:
    ENV_FILE: config/.env.prod
  volumes:
    - .:/app
    - ~/.cache/huggingface:/root/.cache/huggingface

services:
  pawpal_mongodb_dev:
    image: mongodb/mongodb-community-server:latest
    container_name: pawpal_mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      MONGODB_INITDB_ROOT_USERNAME: pawpal_mongodb_dev
      MONGODB_INITDB_ROOT_PASSWORD: pawPalRockHehe
    volumes:
      - ./db:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5

  pawpal-dev:
    <<: *pawpal-common
    container_name: pawpal-dev
    command: python app.py
    ports:
      - "11080:11080"
    networks:
      - backend
      - frontend

  pawpal-streamlit-dev:
    <<: *pawpal-common
    container_name: pawpal-streamlit-dev
    command: streamlit run dashboard.py
    ports:
      - "8501:8501"
    networks:
      - frontend

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - frontend

networks:
  backend:
    internal: true
  frontend:
